### ISSUE TITLE
Unable To Run godot-d_generator "Unexpected ASDF kind"

### ISSUE THREAD

**Issue by Supatier** [GodotNativeTools/godot-d#10]
After running `dub run godot-d:generator`
I get this:
`Building package godot-d:generator in /home/abc/Documents/Projects/git/godot-d/`
`Performing "debug" build using dmd for x86_64.`
`asdf 0.1.5: building configuration "library"...`
`godot-d:generator ~master: building configuration "application"...`
`Linking...`
`Running ./godot-d_generator`
`["./godot-d_generator"]`
`Outputting to default directory ./.`
`asdf.serialization.DeserializationException@/home/abc/.dub/packages/asdf-0.1.5/asdf/source/asdf/serialization.d(1791): Unexpected ASDF kind`
`----------------`
`??:? void asdf.serialization.deserializeValue!(api.c.API).deserializeValue(asdf.asdf.Asdf, ref api.c.API) [0x124a68d1]`
`??:? api.c.API asdf.serialization.deserialize!(api.c.API).deserialize(asdf.asdf.Asdf) [0x124a6818]`
`??:? api.c.API asdf.serialization.deserialize!(api.c.API).deserialize(immutable(char)[]) [0x124a4848]`
`??:? _Dmain [0x124b099e]`
`Program exited with code 1`

**Comment by sheepandshepherd** [comment]
Yeah, it's incompatible with the big overhaul the GDNative API got last week. I'm almost finished updating it - will upload in a day or two.
