### ISSUE TITLE
Unable to build with Ubuntu's version of phobos

### ISSUE THREAD

**Issue by Supatier** [GodotNativeTools/godot-d#17]
I've been testing with Ubuntu and installing ldc + libphobos-ldc2 provided by Ubuntu, it gives me this error:
`../../.dub/packages/asdf-0.1.7/source/asdf/outputarray.d(13): Error: module allocator is in file 'std/experimental/allocator.d' which cannot be read`

It was fixed when using libphobos-ldc2 from the official dlang [repo](https://dlang.org/download.html).
I suggest adding a dependency section in the README.md file.

**Comment by sheepandshepherd** [comment]
Good idea. The readme will need updating anyway after the 2 breaking changes I'll make this week.

That LTS Ubuntu version of LDC is 2 years old and allocators were added to D in 2015. I've just gotten used to downloading LDC manually, since my distro is also slow at keeping D packages updated.
