### ISSUE TITLE
Exception while compiling

### ISSUE THREAD

**Issue by xfactor2000** [GodotNativeTools/godot-d#20]
Hi,
I'm getting error trying to compile test project in examples with dub (Manjaro Linux):

```
Invalid source/import path: /home/anton/godot-d/classes
Invalid source/import path: /home/anton/godot-d/classes
Invalid source/import path: /home/anton/godot-d/classes
Invalid source/import path: /home/anton/godot-d/classes
Performing "debug" build using /usr/bin/ldc2 for x86_64.
godot-d ~master: building configuration "library"...
../../src/godot/c/core.d(4,8): Error: module api is in file 'godot/c/api.d' which cannot be read
import path[0] = /usr/include/dlang/ldc/ldc
import path[1] = /usr/include/dlang/ldc
import path[2] = ../../src
import path[3] = ../../classes
import path[4] = ../../common
/usr/bin/ldc2 failed with exit code 1.
```

**Comment by sheepandshepherd** [comment]
That file is auto-generated from Godot's API. Did you run the API generator first? The steps are [here](https://github.com/GodotNativeTools/godot-d/blob/master/generator/README.md). Basically: obtain one file from the Godot source, one from the Godot binary, and run `dub run godot-d:generator`.

(This annoying step will go away once this is released on DUB and the auto-generated files are included in the DUB package releases.)

**Comment by Supatier** [comment]
Or if you're lazy, `./linux-gen.sh`.

**Comment by xfactor2000** [comment]
Thanks guys, will try later. I am new to  D, really like this language and
hope to see it succeed.

**Comment by xfactor2000** [comment]
Ok,I tried this, obtained the files, ran ``dub rin godot-d:generator``, now getting this:

Building package godot-d:generator in /home/anton/godot-d/
Performing "debug" build using /usr/bin/ldc2 for x86_64.
asdf 0.1.8: target for configuration "library" is up to date.
dxml 0.2.3: target for configuration "library" is up to date.
godot-d:generator ~master: building configuration "application"...
Info: SSE4.2 instructions are not used for ASDF.
../.dub/packages/dxml-0.2.3/dxml/source/dxml/internal.d(85,21): Error: no property 'source' for type 'ByCodeUnitImpl'
../.dub/packages/dxml-0.2.3/dxml/source/dxml/parser/package.d(899,30): Error: template instance dxml.internal.stripBCU!(string, ByCodeUnitImpl) error instantiating
../.dub/packages/dxml-0.2.3/dxml/source/dxml/parser/package.d(3044,1):        instantiated from here: EntityRange!(Config(cast(Flag)true, cast(Flag)true, cast(Flag)true), string)
../.dub/packages/dxml-0.2.3/dxml/source/dxml/dom.d(785,39):        instantiated from here: parseXML!(Config(cast(Flag)true, cast(Flag)true, cast(Flag)true), string)
generator/api/doc.d(16,31):        instantiated from here: parseDOM!(Config(cast(Flag)true, cast(Flag)true, cast(Flag)true), string)
../.dub/packages/dxml-0.2.3/dxml/source/dxml/dom.d(787,14): Error: template instance dxml.dom._parseDOM!(EntityRange!(Config(cast(Flag)true, cast(Flag)true, cast(Flag)true), string), DOMEntity!string) error instantiating
generator/api/doc.d(16,31):        instantiated from here: parseDOM!(Config(cast(Flag)true, cast(Flag)true, cast(Flag)true), string)
../.dub/packages/dxml-0.2.3/dxml/source/dxml/util.d(882,24): Error: no property 'source' for type 'ByCodeUnitImpl'
generator/api/doc.d(127,31): Error: template instance dxml.util.stripIndent!string error instantiating
/usr/bin/ldc2 failed with exit code 1.

**Comment by Supatier** [comment]
What version of godot are you using?
I just tried with 3.0.2-mono and works fine.

**Comment by sheepandshepherd** [comment]
Hmm, I need to remember to test with both compilers. It works with DMD, but I get the same errors with LDC. The errors are in the XML package I added a few days ago, but I'll see if I can track them down anyway...

**Comment by xfactor2000** [comment]
3.0.2—mono

**Comment by sheepandshepherd** [comment]
Looks like that missing function used by DXML was added [recently](https://github.com/dlang/phobos/commit/6d7c2b0ba100b4fc117865abb808baef61f7ec26). The stable LDC for that version of D was released less than 24 hours ago, even. I hate to depend on such recent compilers... hopefully LDC 1.8.0 will be packaged soon. Until then, you could get it directly from [LDC's GitHub release](https://github.com/ldc-developers/ldc/releases/tag/v1.8.0), or switch to DMD (much more up-to-date).

**Comment by xfactor2000** [comment]
I can confirm it worked on DMD
