### ISSUE TITLE
Unable to Emit Signal "pressed". Method not found _on_ExampleOneButton_pressed

### ISSUE THREAD

**Issue by Supatier** [GodotNativeTools/godot-d#23]
The coding style is somewhat inconsistent.
![screenshot from 2018-03-27 07-56-42](https://user-images.githubusercontent.com/19777767/37940764-a6ace03a-3194-11e8-882f-8879beb57c07.png)

![screenshot from 2018-03-27 07-57-14](https://user-images.githubusercontent.com/19777767/37941380-24e8c132-3198-11e8-9804-5f3c24951a1a.png)

but it should work.
Testing all the buttons gives me ```
ERROR: emit_signal: Error calling method from signal 'pressed': 'Node(main_scene.tres.gdns)::_on_ExampleOneButton_pressed': Method not found.
   At: core/object.cpp:1202.
ERROR: emit_signal: Error calling method from signal 'pressed': 'Node(main_scene.tres.gdns)::onExampleTwoButtonPressed': Method not found.
   At: core/object.cpp:1202.
ERROR: emit_signal: Error calling method from signal 'pressed': 'Node(main_scene.tres.gdns)::onExampleThreeButtonPressed': Method not found.
   At: core/object.cpp:1202.
ERROR: emit_signal: Error calling method from signal 'pressed': 'Node(main_scene.tres.gdns)::onExampleFourButtonPressed': Method not found.
   At: core/object.cpp:1202.```

Here's the [project](https://github.com/Supatier/godot-d-examples-one)

**Comment by sheepandshepherd** [comment]
Inside Godot editor and the scene file, they should be referred to as `_on_example_one_button_pressed` and so on. Methods are converted to snake_case (to lowercase and _ added before each former uppercase letter) when they're registered to Godot so the "standard" coding style can be used in both GDScript and D even when using them together.

In case you want to use the original camelCase names everywhere and inside Godot, I could add a compile flag to disable automatic renaming in the whole project... that's been requested once before.

**Comment by Supatier** [comment]
> Inside Godot editor and the scene file, they should be referred to as _on_example_one_button_pressed and so on. Methods are converted to snake_case (to lowercase and _ added before each former uppercase letter) when they're registered to Godot so the "standard" coding style can be used in both GDScript and D even when using them together.

But still, I can't get signals to work.
[gd.zip](https://github.com/GodotNativeTools/godot-d/files/1850829/gd.zip)

**Comment by Supatier** [comment]
It turns out, signal methods can't be camelCase otherwise, `method not found`.

**Comment by sheepandshepherd** [comment]
Alright, will add later this week in 0.0.3. One minor issue is functions like `_fixed_process` still must be registered in snake_case, otherwise Godot won't recognize them. The Rename UDA can be used for now, at least.

**Comment by sheepandshepherd** [comment]
Just added the version specification `GodotNoAutomaticNamingConvention` to disable camelCase->snake_case registration. See the [dub documentation](https://code.dlang.org/package-format?lang=json#build-settings) on how to add it to your dub.json/dub.sdl. For example, `"versions": ["GodotNoAutomaticNamingConvention"],` in JSON.

The issue I mentioned remains for now - you'll still have to manually rename overrides of virtual functions like `_guiInput` to snake_case if their name is different in camelCase.
