### ISSUE TITLE
Unable to Select File in Editor with @Property

### ISSUE THREAD

**Issue by Supatier** [GodotNativeTools/godot-d#26]
![screenshot from 2018-03-30 07-03-20](https://user-images.githubusercontent.com/19777767/38118937-85b8e486-33e8-11e8-886c-43cf0d2eb271.png)

The variable shows up but you can't select anything.
![screenshot from 2018-03-30 07-03-39](https://user-images.githubusercontent.com/19777767/38118949-a0baa0f8-33e8-11e8-85c5-e51064a230a2.png)

**Comment by sheepandshepherd** [comment]
I'm not very familiar with Godot's File class, but I don't think it can be used as a property. I've seen selectable file properties in GDScript that use Resource or String (for path) as their type, plus some kind of property hint. But there's almost no documentation on Godot's [property hints](https://godot.readthedocs.io/en/3.0/classes/class_@globalscope.html#enum-globalscope-propertyhint)...

These work, and you can use File to load what's at the paths:
```d
	@Property(Property.Hint.file, ".txt")
	String fileInRes;
	@Property(Property.Hint.globalFile, ".txt")
	String fileAnywhere;
```

Using a Resource is much easier, but of course only works with Resource types.

**Comment by Supatier** [comment]
So that's the proper syntax. It should be in the readme.

**Comment by sheepandshepherd** [comment]
Sounds reasonable. I added a method and a property to the readme example.
