### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by EdnGameDev** [GodotNativeTools/godot-d#41]
I have no idea if godot-d should work with Godot 3.1 recent build, but in case it should.

After generating the classes, the module godot.slider is generated without importing godot.control, causing bug in the property focusMode, and Godot is not being able to see the methods with the annotation Method, I already tested using the example asteroids and it seems that the same thing happens.

**Comment by sheepandshepherd** [comment]
Just tried this with the latest Godot commit, but `godot.slider` does import `godot.control` for me. This sounds like an issue that got fixed [a few months ago](https://github.com/GodotNativeTools/godot-d/commit/1a3d26fd2225630df7db470c9942cecadb038b1a) -- are you using an older version of Godot-D maybe?

**Comment by EdnGameDev** [comment]
Well, I was using the latest version of godot-d from this repo and unofficial build from https://hugo.pro/projects/godot-builds/

**Comment by EdnGameDev** [comment]
With the official build the godot import problem doesn't exist, just the second problem that persists

**Comment by sheepandshepherd** [comment]
In what situation are the methods missing? Are you calling them from GDScript?

Just a guess, but maybe you're referring to them in camelCase from inside Godot -- for consistency with both styles, they're converted to Godot's snake_case before registration, so any usage outside D should use that. A few people have said that this isn't obvious, so I mentioned it in the readme and documentation, but I could add this info to the comments in the examples as well.

If you want to call your methods with the same name consistently *everywhere*, you can add `"versions": ["GodotNoAutomaticNamingConvention"]` to your dub.json.

**Comment by EdnGameDev** [comment]
I am using camelCase for methods like _ready and _enterTree, i am not even using signals right now, and to ensure that I was doing it right, I looked at your example asteroids. Since these "lifecycle" methods of Node wasn't being called in my test project, I tried to run the asteroids example and it wasn't running in it too.

**Comment by EdnGameDev** [comment]
Oh my goodness, that's it then, thank you very much, I will look at the example and see the changes.

**Comment by EdnGameDev** [comment]
Yeah, that's it, now the nativescript class name need to have the full module name and the class name. As you said, it is a hard stuff to see because of the lack of a proper error message.
