### ISSUE TITLE
Compiler error with getter and no setter

### ISSUE THREAD

**Issue by Putnam3145** [GodotNativeTools/godot-d#44]
```
C:\Users\Putnam\AppData\Local\dub\packages\godot-d-0.1.2\godot-d\src\godot\d\register.d(314,41): Error: tuple index 0 exceeds 0

C:\Users\Putnam\AppData\Local\dub\packages\godot-d-0.1.2\godot-d\src\godot\d\register.d(356,18): Error: cannot implicitly convert expression & emptySetter of type extern (C) void function(godot_object self, void* methodData, void* userData, godot_variant value) to extern (C) void function(godot_object, void*, void*, godot_variant*)
```

(Repeated for every setterless getter `@Property` I have)

Posting an issue to make sure I'm not missing anything obvious before I jump into fixing it myself. Here's an example of one said property causing the problem:

```
    @Property pure float compressiveStrainAtYield() const
    {
        return compressiveStrength/bulkModulus;
    }
```

EDIT: why is this code markdown harder than any other code markdown i've used?
EDIT 2: ADHD editing, sorry

**Comment by karroffel** [comment]
(totally unrelated to the topic in question, there is a "preview" button when you are creating an issue or a comment that shows you how the rendered markdown looks like)

**Comment by Putnam3145** [comment]
I got kind of a hacky solution together at https://github.com/Putnam3145/godot-d/commit/1c8b9ff92f93a1a9499db1a97e46f375bf93c9d6--my compiler errors are of my own doing, after this fix.

**Comment by sheepandshepherd** [comment]
Your fix is exactly right, actually - I forgot that short-curcuiting doesn't work at compile time. This and the 2 typos are fixed now, and actually tested in the test project.
