### ISSUE TITLE
Compiler Error Using NoDRuntime Enum

### ISSUE THREAD

**Issue by matthew1006** [GodotNativeTools/godot-d#46]
When attempting to use the NoDRuntime enum as instructed in register.d I get the following compiler error:
`Error: enum 'godot.d.register.NoDRuntime' is forward referenced looking for base type`
I've found that giving NoDRuntime a value fixes this issue:
`enum NoDRuntime = "NoDRuntime";`

**Comment by sheepandshepherd** [comment]
I changed the enum to more clearly describe what it's doing. Pass `LoadDRuntime.no` in its place now.

Side note: when I tested this, I noticed that D now loads the runtime automatically as soon as it's used, something that was also mentioned in the changelogs a few DMD versions ago.
