### ISSUE TITLE
Rename Attribute On Classes

### ISSUE THREAD

**Issue by matthew1006** [GodotNativeTools/godot-d#47]
Currently classes are registered with their fully qualified names (e.g. module.class). This may not always be desired; For example if you have libraries for different platforms written in different languages then your classes will need the same registered name in each library for your gdns files to work.

The registration of classes in register.d suggests that the Rename attribute is intended to work with classes
```
static if(hasUDA!(T, Rename)) enum immutable(char*) name = TemplateArgsOf!(
		getUDAs!(T, Rename)[0])[0];
	else enum immutable(char*) name = fullyQualifiedName!T;
```

but when I tried it I got this compiler error:
`Error: template std.traits.TemplateArgsOf does not match any template declaration`

I found that changing it to
```
static if(hasUDA!(T, Rename)) enum immutable(char*) name = godotName!T;
	else enum immutable(char*) name = fullyQualifiedName!T;
```
does allow the Rename attribute to work with classes.

**Comment by sheepandshepherd** [comment]
Thanks for the fix. I'm not sure why TemplateArgsOf isn't working here, but just using godotName is much better.

**Comment by matthew1006** [comment]
It's because the Rename struct isn't a template so it doesn't have template arguments.
If Rename was defined like this:
`struct Rename(string name) {}`
and used like this:
`@Rename!("class_name")`
then TemplateArgsOf would work but how it works now is probably better.

**Comment by sheepandshepherd** [comment]
Oh right, that makes sense. I forgot Rename was implemented like that - had it confused with OnReady, probably.
