### ISSUE TITLE
Register whole modules?

### ISSUE THREAD

**Issue by sheepandshepherd** [GodotNativeTools/godot-d#7]
GodotNativeInit would be even more convenient if we could pass a module name to register every script class in that module. Unfortunately there's no `isModule` trait, and `__traits(allMembers, <module>)` doesn't work. Is there any other way to iterate over all of a module's classes (better yet including public imports)?

**Comment by karroffel** [comment]
Sounds nice tbh 👌  Make it happen ™️

**Comment by sheepandshepherd** [comment]
Doubt this is possible with D. However, I can eventually use the [editor import plugin](https://github.com/sheepandshepherd/godot-d-importer) to auto-generate the list of classes to register. This would improve usability a lot.
