### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by EdnGameDev** [GodotNativeTools/godot-d#8]
I tried to build it and it gave me an error:

register.d(193,49): Error: array index [0] is outside array bounds [0 .. 0]
register.d(86,5): Error: template instance godot.d.register.register!(TestScript) error instantiating

It happens only when I try to use the annotation @ Method in some method, in that case the _ready() method. if I remove the annotation it build normally, but it will not execute the _ready() method when I attach the script to a Node.

**Comment by sheepandshepherd** [comment]
Hmm, a strange bug. It seems to not be detecting the `@Method` attribute inside the loop over methods. I've had similar bugs with loops before, but still not sure exactly when this happens...

Could you test again with the change I just made? If it's still causing problems, post the version/platform of the compiler you're using and the TestScript where it's happening.

If this change *does* fix your error message, I might have a few other buggy loops where I need to apply this fix.

**Comment by EdnGameDev** [comment]
Sure, I will test now. I can post now the TestScript

`import godot.c;

import godot;
import godot.node;

import std.stdio;



class TestScript : GodotScript!Node
{
	@Method
	void ready()
	{
		print("TestScript.ready(): It is just a test message");
	}
}

mixin GodotNativeInit!
(
	TestScript,
	(){writeln("GodotNativeInit func");}
);

mixin GodotNativeTerminate!
(
	(){writeln("GodotNativeTerminate func");}
);
`

**Comment by EdnGameDev** [comment]
It still with the same error.

**Comment by EdnGameDev** [comment]
I followed your suggestion and I updated the DMD to the latest version and it fixed the problem, thank you.

**Comment by sheepandshepherd** [comment]
Excellent, it must have been an older language bug then.
