### ISSUE TITLE
Error in the API Generator

### ISSUE THREAD

**Issue by EdnGameDev** [GodotNativeTools/godot-d#9]
I tried to generate the API with the generator and it generated invalid code. The generator, in some files, generated method arguments with identifier names which is D reserved words, like override and interface, causing problems to build.

**Comment by sheepandshepherd** [comment]
Thanks, I forgot to put those on the keyword list. Eventually I'll get around to including one of the D parser libraries in the generator to catch *all* invalid names.

**Comment by EdnGameDev** [comment]
=).
